---
Name: betamask
Before: adminthemes
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\Betamask\Extension\LeftAndMain
  admin_themes:
    - 'betamask'

---
Name: betamask_featureflag
After: featureflag
---
# Features enable/disable by each CMS user
SilverStripe\FeatureFlag\Extension\MemberConfiguration:
  features:
    FeatureFlag_Silverplasty:
      Label: 'Betamask'
      Help: |
        We should put a description here about what this feature is lorem ipsum dolor sit amet, consectetur
        adipiscing elit. Proin efficitur condimentum mi, in porta velit faucibus non.
